"""add active field to products

Revision ID: 03585315ac30
Revises: aa2772454cb2
Create Date: 2025-12-14 20:59:58.521431

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03585315ac30'
down_revision = 'aa2772454cb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active', sa.Boolean(), server_default=sa.text('1'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('active')

    # ### end Alembic commands ###
