"""Add created_at with server_default

Revision ID: 803d23f369cc
Revises: 03585315ac30
Create Date: 2025-12-14 21:29:40.703443

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '803d23f369cc'
down_revision = '03585315ac30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
